### ISSUE TITLE
Cannot fix wrong ja-JP trasnlation on Crowdin

### ISSUE THREAD

**Issue by unasuke** [electron/i18n#1599]
## What

The name of modules for the Main Process "Notification" translates to the Japanese word "通知".

But this word should not translate to any language.

> Do not translate Electron classes, method names, event names, etc.

* https://github.com/electron/i18n/blob/master/content/9-x-y/ja-JP/docs/README.md
    * [7e785868](https://github.com/electron/i18n/blob/7e7858687c470e0f41b8dc0416afef2b1f7502fa/content/9-x-y/ja-JP/docs/README.md)
* https://github.com/electron/i18n/blob/master/content/10-x-y/ja-JP/docs/README.md
    * [7e785868](https://github.com/electron/i18n/blob/7e7858687c470e0f41b8dc0416afef2b1f7502fa/content/10-x-y/ja-JP/docs/README.md)
* https://github.com/electron/i18n/blob/master/content/12-x-y/ja-JP/docs/README.md
    * [7e785868](https://github.com/electron/i18n/blob/7e7858687c470e0f41b8dc0416afef2b1f7502fa/content/12-x-y/ja-JP/docs/README.md)
* https://github.com/electron/i18n/blob/master/content/current/ja-JP/docs/README.md
    * [7e785868](https://github.com/electron/i18n/blob/7e7858687c470e0f41b8dc0416afef2b1f7502fa/content/current/ja-JP/docs/README.md)

However, this word cannot edit on crowdin.

![image](https://user-images.githubusercontent.com/4487291/100544200-7176e580-3297-11eb-8bb4-d10466025c65.png)

> Don't open pull requests to translate Electron; instead, do all translations on Crowdin.

What should we do?

**Comment by erickzhao** [comment]
Hey @unasuke, I'm not too clear on why this is the case, but it seems like the following pull from CrowdIn fixes the issue

https://github.com/electron/i18n/pull/1598/files

**Comment by unasuke** [comment]
Wow, It's good. Thank you @erickzhao . I close this.
