### ISSUE TITLE
Quickstart - translation miss on command

### ISSUE THREAD

**Issue by tavinus** [electron/i18n#1655]
**EDIT: This is in BRAZILIAN PORTUGUESE**  
_(I just noticed that the link has no language tag. I can't force the language...)_

Here:  
https://www.electronjs.org/docs/tutorial/quick-start#install-electron  
  
`mkdir` and `cd` should point to the same dir
```bash
mkdir my-electron-app && cd meu-electron-app
```
So
```bash
mkdir meu-electron-app && cd meu-electron-app
```
If you copy/paste the whole thing you end up initializing in the parent folder
```bash
mkdir my-electron-app && cd meu-electron-app
npm init -y
npm i --save-dev electron
```

**Comment by erickzhao** [comment]
Hey @tavinus, I've moved this issue over to our i18n repo.

For information on how to contribute to our user-sourced translations, check out this repo's [CONTRIBUTING.md](https://github.com/electron/i18n/blob/master/contributing.md).

I've modified this string in the CrowdIn interface, so it should be updated on the website within the next day or two.
