### ISSUE TITLE
Extra space in landing

### ISSUE THREAD

**Issue by x-N0** [electron/i18n#1684]
![imagen](https://user-images.githubusercontent.com/51316342/105467822-f7e6ec80-5c74-11eb-800e-786436a9c0bd.png)

Typo, theres just an extra space in the spanish version of the landing page's title, at the end.

Found the locale file -> https://github.com/electron/i18n/blob/master/content/current/es-ES/website/locale.yml

But all the "HTML y CSS" appearances seem to not have the space, so... ??

**Comment by x-N0** [comment]
Looked into [electron.org repo's home view](https://github.com/electron/electronjs.org/blob/master/views/home.hbs) and nothing, hmm...

**Comment by erickzhao** [comment]
Hey @x-N0, seems to me like that extra space isn't there?

![image](https://user-images.githubusercontent.com/16010076/105525905-8cae1200-5c96-11eb-88dd-12b42c1790c8.png)
