### ISSUE TITLE
Missing '{' in Zh translations of quickstart

### ISSUE THREAD

**Issue by sdutwsl** [electron/i18n#1743]
[https://www.electronjs.org/docs/tutorial/quick-start#main-and-renderer-processes](https://www.electronjs.org/docs/tutorial/quick-start#main-and-renderer-processes)
```
// 在主进程中
const { ipcMain } = require('electron')

ipcMain.handle('exper-action', (evidence, ...args) =>
  // ... 代表渲染器操作
})
```

**Comment by erickzhao** [comment]
Hi @sdutwsl, these can be fixed in our CrowdIn interface here: https://crowdin.com/translate/electron/174660/en-zhcn?filter=basic&value=0

I've done it for the reported issue! This repo should receive the update within a day.
