### ISSUE TITLE
Strange Wallet Authentication Information in German Translation of faq.md

### ISSUE THREAD

**Issue by yves147** [electron/i18n#1766]
![grafik](https://user-images.githubusercontent.com/54778078/110015233-ed178100-7d23-11eb-8e0c-ae45ad32bf46.png)

The current german online version of the faq.md file reachable at https://www.electronjs.org/docs/faq includes
some (maybe) authentication details or otherwise just strange text including the keywords (translated):
_Your API-Key, Wallet, Public Key, etc._

I searched for the file on Crowdin. Here's the link for the version: https://crowdin.com/translate/electron/174546/en-de

**And also the direct link to the strange text:** [https://www.electronjs.org/docs/faq#0x6694d8de...](https://www.electronjs.org/docs/faq#0x6694d8de7be8ee5631bed9502bd5824b7f9470e6-api-schl%C3%BCsselstatus-aktiv-dein-api-schl%C3%BCssel-cdcadfe6a25125e3a1a8e12eae924944-private-key-papier-wallet-kwnd42xq8c2wqdidnbw7kt9wnjac1gdh4arnnmk37bzhw9xklat4-revaller-1d6d-5622-531c-b0d4-3268-97db-b172-txid-pubkey-0x6694d8de7be8ee5631bed9502bd5824b7f9470e6-585636460874565370753570386791880216602985394406-handy-key-cwallet-0x9f11e2d02668749520)

The original text was _https://crowdin.com/translate/electron/7/en-de?filter=basic&value=0_

Hope you fix it ASAP and maybe contact the person that just leaked their details.

**Comment by yves147** [comment]
btw i just recognized it seems other people that have the same operating system and are using the same browser etc. do not see this version at /docs/faq

**Comment by roeald** [comment]
I can replicate it. DE-DE as a browser language.

**Comment by erickzhao** [comment]
@yves147 Thank you for the report! It seems like the translation was originally machine-generated. I've updated the string in CrowdIn.
