### ISSUE TITLE
[Doc Error]: the sample code in the "Electron - BrowserView" Chinese documentation was mistranslated

### ISSUE THREAD

**Issue by linying1991** [electron/i18n#1879]
Hello, the sample code in the "Electron - BrowserView" Chinese documentation was mistranslated, but I don't have permission to change it, could you please confirm and correct it? (The content is machine translated)
https://www.electronjs.org/docs/api/browser-view#%E7%A4%BA%E4%BE%8B

error (now)
![1](https://user-images.githubusercontent.com/38310238/118901818-c5a97b00-b946-11eb-8c02-8d6d0a501896.png)

correct
![2](https://user-images.githubusercontent.com/38310238/118901828-c9d59880-b946-11eb-85af-e4628a77b0f7.png)

I don't have permission to change it
![118831581-78032300-b8f2-11eb-87d0-18b62807bebb](https://user-images.githubusercontent.com/38310238/118901860-e671d080-b946-11eb-8bc7-4747d703aa47.png)

**Comment by linying1991** [comment]
i try to pull request [https://github.com/electron/i18n/pull/1880](https://github.com/electron/i18n/pull/1880)

**Comment by erickzhao** [comment]
Should be updated in CrowdIn now. Sorry for the delay!
