### ISSUE TITLE
[Suggestion] limited proofreader role of specific language

### ISSUE THREAD

**Issue by dakeshi** [electron/i18n#253]
I find out there are broad proofreader role in electron crowdin project.
There are two ways to give a proofreader permission to users on Crowdin.

- changing translator role to proofreader.
- add proofreader permission for specific language(recommended) with translator role

![translators](https://user-images.githubusercontent.com/8563047/36571531-7fe26656-187a-11e8-9b98-6fc60be4e57a.png)

In the current setting(https://crowdin.com/project/electron/translators), every proofreader can handle every languages. Actually, it doesn't make sense because it is impossible to know every languages. So, I think that setting up limited proofreader role per language based on what they have translated would help to make better translation quality.

**Comment by dakeshi** [comment]
Thanks for your reply. For the project management, it is very import to limit its proof-reader's role to specific lang.  And describing how to set up limited proof-reader role could be helpful to someone who want to start to translation projects. 

I think that adding separate section like Developing electron-i18n would be better because most of translators don't need to know about this. I'll open PR as soon as possible.

**Comment by dakeshi** [comment]
refer to https://github.com/electron/i18n/pull/299

**Comment by dakeshi** [comment]
The description about limited proofreader role on crowdin has added in CONTRIBUTING.md

**Comment by zeke** [comment]
:tada: Thanks again, @dakeshi
