### ISSUE TITLE
rename repo to i18n

### ISSUE THREAD

**Issue by zeke** [electron/i18n#255]
The Node.js internationalization repo is called https://github.com/nodejs/i18n (without a prefix) and @vanessayuenn and I are feeling a little jealous.

Would anyone object to us renaming this repo to `electron/i18n`? (Of course GitHub will redirect if anyone visits the old `electron-electron-i18n` URL.

**Comment by FranzDeCopenhague** [comment]
I like it

**Comment by zeke** [comment]
Did it. #yolo. Leaving this open for a followup PR that updates references in the code and docs.
