### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by nunojesus** [electron/i18n#260]
Helo!

I saw in crowdin that you have Portuguese from Brazil, do you want also Portuguese from Portugal?
If you want just say it!
Greetings!

**Comment by zeke** [comment]
Based on the recent conversation in #281, we are thinking it's best to not have numerous dialects for now, as it can create much more work for translators, and the differences between the translated content for the two languages may be very small.

For now I will close this issue, but if the differences between the two Brazilian languages are significant, and if there is enough interest from Portugal-based developers, we can certainly enable the new language in Crowdin.
