### ISSUE TITLE
New translation locale.yml for Spanish-Venezuela 

### ISSUE THREAD

**Issue by FranzDeCopenhague** [electron/i18n#281]
I have noticed a new translation locale.yml for Spanish-Venezuela https://github.com/electron/i18n/commit/feca06e

Don't know how is the process of adding languages and regions but it could be a big problem if there is no control about adding new languages or countries. In case of Spanish at computer science level, there is not different at all and it will generate a lot of duplications in translations.
* https://crowdin.com/project/electron/esve
* https://crowdin.com/project/electron/es

There are 20 countries which official language is Spanish.

es-AR | Spanish - Argentina
es-BO | Spanish - Bolivia
es-CL | Spanish - Chile
es-CO | Spanish - Colombia
es-CR | Spanish - Costa Rica
es-DO | Spanish - Dominican Republic
es-EC | Spanish - Ecuador
es-SV | Spanish - El Salvador
es-GT | Spanish - Guatemala
es-HN | Spanish - Honduras
es-MX | Spanish - Mexico
es-NI | Spanish - Nicaragua
es-PA | Spanish - Panama
es-PY | Spanish - Paraguay
es-PE | Spanish - Peru
es-PR | Spanish - Puerto Rico
es-ES | Spanish - Spain
es-UY | Spanish - Uruguay
es-VE | Spanish - Venezuela

**Comment by zeke** [comment]
Thanks for opening this issue, @FranzDeCopenhague. I was thinking the same thing but have historically honored all requests to add new languages. Do you think that the best approach is to just have one "Spanish" translation? If so, we can easily disable the Venezuelan language. I'd also be curious to hear what other Spanish speakers think.

cc'ing Spanish speakers who filled out the [translator survey](https://goo.gl/forms/b46sjdcHmlpV0GKT2): @LFiungano14 @Raul6469 @araymoises @felipet-vsouza @rafaelstz

**Comment by FranzDeCopenhague** [comment]
Yes, I think the best approach is just having only one Spanish translation. We can extrapolate the same argument to en-US versus en-GB

**Comment by Raul6469** [comment]
Hi! I agree with @FranzDeCopenhague, having one spanish translation is enough in my opinion. I might be wrong as I'm spanish, but I do think that there is very little to no difference between them.

**Comment by rafaelstz** [comment]
Hi guys, I agree as well, there's no enough changes to justify many versions.

**Comment by zeke** [comment]
Thanks for the feedback, everyone. I have disabled Venezuelan Spanish on Crowdin. This is the first time we've disabled a target language. It should be fine, but let's keep an eye out for any issues this might cause on this repo.

Closing.
