### ISSUE TITLE
Pull Requests from forks doesn't trigger semantic releases

### ISSUE THREAD

**Issue by zeke** [electron/i18n#296]
Was wondering why PR #295 didn't trigger a release to npm. Turns out it's because environment variables are not available to forked repos.

From https://travis-ci.org/electron/i18n/builds/362287730:

```
semantic-release WARN invalid config loglevel="notice"
semantic-release ERR! init No github token specified. ENOGHTOKEN
semantic-release ERR! init No npm token specified. ENONPMTOKEN
```

@gr2m do you know of a workaround for this?

cc @Shivam-Miglani

**Comment by gr2m** [comment]
environment variables that are set to private are accessible to forks.

Why would you want a release happen from a pull request? Usually you want the release after the PR is merged into the main branch, no?

**Comment by HashimotoYT** [comment]
Closing as fixed in some time.
