### ISSUE TITLE
New translation language

### ISSUE THREAD

**Issue by TzviRonen** [electron/i18n#319]
Hi, I am willing to start translation to Hebrew but i'm unable to open new translation language in crowdin Can anyone open it for me?

I have  sent a message already to Alexandra Bourne (albourne 1) and Electron Globo (globo) from crowdin
but no answer.

**Comment by zeke** [comment]
Hi @TzviRonen I can set that up for you.

**Comment by zeke** [comment]
https://crowdin.com/project/electron/he

Please have a look at https://github.com/electron/i18n/blob/master/contributing.md before you get started, and thanks for your help!
