### ISSUE TITLE
How to contribute to (german) translation?

### ISSUE THREAD

**Issue by michagrandel** [electron/i18n#391]
Hi there,

I'm thinking about contributing in the translation of electron to german. But I'm not sure where to begin. I know, the translation is managed on [crowdin](https://crowdin.com/project/electron/de). I know how to use the tools around there, but this doesn't help much:

Is there any translation team I can contact? Who approves translations? Which courtesy form ("Du" or "Sie") should I use? Are there some general guidelines?

This is my first big open source project where I feel like I can provide some help, but currently, I feel a little lost. Someone there who can clarify some of my points?

Thank you!
Micha

**Comment by HashimotoYT** [comment]
Answered above.
