### ISSUE TITLE
Request: Romanian language for translation

### ISSUE THREAD

**Issue by vladutilie** [electron/i18n#415]
Hello,

May someone add Romanian (locale code is ro_RO) language for translation in https://crowdin.com/project/electron and maybe a descripted way to request this type of stuff in the documentation.
I am willing to help with this locale.

Thank you!

**Comment by zeke** [comment]
I've enabled the Romanian language on the project: https://crowdin.com/project/electron/ro#

Very sorry for the long delay, @vladutilie. Please let me know how it goes.
