### ISSUE TITLE
Crowdin link broken

### ISSUE THREAD

**Issue by vladutilie** [electron/i18n#476]
Hello,

In the documentation from [here](https://github.com/electron/i18n/blob/master/contributing.md#adding-a-language) the link to crowdin is broken.

Maybe there is a need of permissions or something.

Thank you!

**Comment by BinaryMuse** [comment]
Hi, @vladutilie,

The section that that link is found in is for folks on the team who develop the i18n module and manage the Crowdin project. Sorry for the confusion.
