### ISSUE TITLE
Long code blocks are truncated in Crowdin UI

### ISSUE THREAD

**Issue by zeke** [electron/i18n#511]
Example: https://crowdin.com/translate/electron/112/en-fr

The source file at https://github.com/electron/electron/blob/master/docs/api/touch-bar.md has a long JS code block. When viewing this block in the Crowdin UI, only a portion of the code is displayed:

![screen shot 2018-11-27 at 9 37 41 am](https://user-images.githubusercontent.com/2289/49100159-1af9eb00-f228-11e8-95ea-2a2e38ad9bca.png)

ref: https://github.com/electron/i18n/pull/504

**Comment by Andrulko** [comment]
Thanks a lot for reporting, @zeke! Checking what can we improve and make this element available for translation

**Comment by Andrulko** [comment]
@zeke The parser works as you expect now, the source file was re-uploaded:
https://crowdin.com/translate/electron/6596/en-fr

**Comment by HashimotoYT** [comment]
Closing as fixed.
